### ISSUE TITLE
Concurrent map read/write in findAlias

### ISSUE THREAD

**Issue by xlab** [aerospike/aerospike-client-go#135]
Hi! I'm getting this under heavy load:

```
fatal error: concurrent map read and map write

2016-07-05T19:09:53.516Z goroutine 241 [running]:
2016-07-05T19:09:53.516Z runtime.throw(0x13e62e0, 0x21)
2016-07-05T19:09:53.516Z 	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc82d791990 sp=0xc82d791978
2016-07-05T19:09:53.516Z runtime.mapaccess1(0xf10b80, 0xc8203308a0, 0xc8394d2c00, 0xc8394d2c00)
2016-07-05T19:09:53.516Z 	/usr/local/go/src/runtime/hashmap.go:289 +0x5a fp=0xc82d7919d8 sp=0xc82d791990
2016-07-05T19:09:53.516Z github.com/aerospike/aerospike-client-go.(*Cluster).findAlias(0xc82017a000, 0xc8394d2c00, 0xbb8)
2016-07-05T19:09:53.516Z 	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/cluster.go:285
```

Commit of the vendored package: `92f8ca8da48f9f7324f4f475bad140c217b693fb`.
I hope this helps.

**Comment by khaf** [comment]
Thanks, will take care of it ASAP.

**Comment by khaf** [comment]
Should be fixed in master.

**Comment by xlab** [comment]
Yes it seems to be fixed, I'll reopen if notices something like this again. Thanks!
