### ISSUE TITLE
"cap out of range" runtime panic

### ISSUE THREAD

**Issue by alicebob** [aerospike/aerospike-client-go#136]
Hi,
I've upgraded our Go client to the latest version yesterday and now we're getting these panics every now and then:

```
2016-07-06_18:41:41.19003 panic: runtime error: makeslice: cap out of range
2016-07-06_18:41:41.19005 
2016-07-06_18:41:41.19006 goroutine 297476140 [running]:
2016-07-06_18:41:41.19007 panic(0xc6fc40, 0xc8303739a0)
2016-07-06_18:41:41.19007       /usr/local/go/src/runtime/panic.go:464 +0x3e6
2016-07-06_18:41:41.19008 .../vendor/github.com/aerospike/aerospike-client-go.(*unpacker
).unpackCDTMap(0xc82cccea10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016-07-06_18:41:41.19008       .../vendor/github.com/aerospike/aero
spike-client-go/unpacker.go:127 +0x74
2016-07-06_18:41:41.19010 .../vendor/github.com/aerospike/aerospike-client-go.(*unpacker
).unpackMap(0xc82cccea10, 0x0, 0x0, 0x0, 0x0, 0x0)
2016-07-06_18:41:41.19011       .../vendor/github.com/aerospike/aero
spike-client-go/unpacker.go:103 +0x141
2016-07-06_18:41:41.19012 .../vendor/github.com/aerospike/aerospike-client-go.(*unpacker
).unpackObject(0xc82cccea10, 0xc82aaa9200, 0x0, 0x0, 0x0, 0x0)
2016-07-06_18:41:41.19012       .../vendor/github.com/aerospike/aero
spike-client-go/unpacker.go:368 +0x23f
2016-07-06_18:41:41.19014 .../vendor/github.com/aerospike/aerospike-client-go.(*unpacker
).unpackMapNormal(0xc82cccea10, 0xf, 0xd8e59, 0x0, 0x0)
2016-07-06_18:41:41.19014       .../vendor/github.com/aerospike/aero
spike-client-go/unpacker.go:117 +0x100
2016-07-06_18:41:41.19015 .../vendor/github.com/aerospike/aerospike-client-go.(*unpacker
).unpackMap(0xc82cccea10, 0xf, 0x0, 0x0, 0x0, 0x0)
2016-07-06_18:41:41.19016       .../vendor/github.com/aerospike/aero
spike-client-go/unpacker.go:105 +0x1dd
2016-07-06_18:41:41.19016 .../vendor/github.com/aerospike/aerospike-client-go.(*unpacker
).UnpackMap(0xc82cccea10, 0x0, 0x0, 0x0, 0x0)
2016-07-06_18:41:41.19017       .../vendor/github.com/aerospike/aero
spike-client-go/unpacker.go:98 +0xf4
2016-07-06_18:41:41.19017 .../vendor/github.com/aerospike/aerospike-client-go.bytesToPar
ticle(0x13, 0xc827d32000, 0x4000, 0x4000, 0xf, 0x2e0, 0x0, 0x0, 0x0, 0x0)
2016-07-06_18:41:41.19018       .../vendor/github.com/aerospike/aero
spike-client-go/value.go:659 +0x5d1
2016-07-06_18:41:41.19019 .../vendor/github.com/aerospike/aerospike-client-go.(*readComm
and).parseRecord(0xc82d94d880, 0x1, 0x0, 0x278c5d000083a7, 0x2ef, 0x0, 0x0)
2016-07-06_18:41:41.19019       .../vendor/github.com/aerospike/aerospike-client-go/read_command.go:164 +0x425
2016-07-06_18:41:41.19020 .../vendor/github.com/aerospike/aerospike-client-go.(*readCommand).parseResult(0xc82d94d880, 0x7f6cc982db88, 0xc82d94d880, 0xc82056ac80, 0x0, 0x0)
2016-07-06_18:41:41.19020       .../vendor/github.com/aerospike/aerospike-client-go/read_command.go:111 +0xc59
2016-07-06_18:41:41.19021 .../vendor/github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc82e29a840, 0x7f6cc982db88, 0xc82d94d880, 0x0, 0x0)
2016-07-06_18:41:41.19022       .../vendor/github.com/aerospike/aerospike-client-go/command.go:1055 +0xb81
2016-07-06_18:41:41.19022 .../vendor/github.com/aerospike/aerospike-client-go.(*readCommand).Execute(0xc82d94d880, 0x0, 0x0)
2016-07-06_18:41:41.19023       .../vendor/github.com/aerospike/aerospike-client-go/read_command.go:258 +0x68
2016-07-06_18:41:41.19024 .../vendor/github.com/aerospike/aerospike-client-go.(*Client).Get(0xc8207ea1e0, 0xc8201d2a40, 0xc8314d10e0, 0xc82f780ce0, 0x2, 0x2, 0xc8314d10e0, 0x0, 0x0)
2016-07-06_18:41:41.19024       .../vendor/github.com/aerospike/aerospike-client-go/client.go:308 +0x3ae
<our code from here on>
```

It talks to a client of  3.7.4.1 servers. If needed I can figure out what the previous version was we used. Anything else I can provide?

**Comment by khaf** [comment]
Do you use CDT/Ordered Maps?

**Comment by alicebob** [comment]
Yes, we use complex data types, nested maps, with Lua functions to add values to them. We sometimes make values which are too big for a single record, in which case the Lua function returns an error. The maps are unordered, afaics.

**Comment by robx** [comment]
To clarify, we use CDTs in the sense of "not just integers", or in the sense of the aerospike documentation (https://www.aerospike.com/docs/guide/data-types.html, https://www.aerospike.com/docs/guide/cdt-map.html). I don't think we use "CDT/Ordered Maps". But I haven't seen those defined anywhere, so it's a bit fuzzy.

**Comment by khaf** [comment]
Fix is in master.

**Comment by alicebob** [comment]
We've ran it over the weekend and no crashes anymore. Thanks!
