### ISSUE TITLE
Panic - slice bounds out of range in parseRecord

### ISSUE THREAD

**Issue by xlab** [aerospike/aerospike-client-go#138]
Hi! I'm getting this under heavy load:

```
panic: runtime error: slice bounds out of range
 	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command_get.go:134 +0x34c
 goroutine 101580 [running]:
 panic(0x115ca80, 0xc82000a090)
 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
 github.com/aerospike/aerospike-client-go.(*baseMultiCommand).readBytes(0xc8857080d0, 0xffffffffffffff29, 0x0, 0x0)
 	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command.go:176 +0x7e2
 	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/client.go:1468 +0x2ca
 github.com/aerospike/aerospike-client-go.(*batchCommandGet).parseRecord(0xc8858ca000, 0xc8a511a050, 0x2, 0x2a2e70000004f, 0x14, 0x0, 0x0)
 github.com/aerospike/aerospike-client-go.(*batchCommandGet).parseRecordResults(0xc8858ca000, 0x7faa6415c0d8, 0xc8858ca000, 0x20d0, 0x8, 0x0, 0x0)
 	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command_get.go:104 +0x6aa
 github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseResult(0xc8857080d0, 0x7faa6415c0d8, 0xc8858ca000, 0xc858823a40, 0x0, 0x0)
 	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command.go:100 +0x29c
 github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc88852a120, 0x7faa6415c0d8, 0xc8858ca000, 0x0, 0x0)
 created by github.com/aerospike/aerospike-client-go.(*Client).batchExecute
 	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/command.go:1057 +0xa4a
 github.com/aerospike/aerospike-client-go.(*batchCommandGet).Execute(0xc8858ca000, 0x0, 0x0)
 	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command_get.go:149 +0x68
 github.com/aerospike/aerospike-client-go.(*Client).batchExecute.func1(0xc88ca32400, 0xc8807fa690, 0xc88ca32028, 0xc88cab80c0, 0xc8202bc1e0, 0xc88852a0c0)
 	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/client.go:1463 +0x86
```

Commit of the vendored package: 92f8ca8da48f9f7324f4f475bad140c217b693fb.
It might be a bit old, I'll try to update the package to the newest master commit and see it that helps.

Also, we reconfigured the cluster just before panics appeared, so it may be a problem in correlation with resharding.

**Comment by khaf** [comment]
I was just getting ready to release the fix to your other report! I'll have a look and release the fix for both tomorrow. The rebalancing hint was invaluable.

**Comment by xlab** [comment]
Thanks, that'd help a lot. Also related:

panic: runtime error: index out of range in `parseRecordResults`

```
panic(0x1102d40, 0xc82000a080)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/aerospike/aerospike-client-go.(*batchCommandGet).parseRecordResults(0xc8e977b920, 0x7fc0ec539138, 0xc8e977b920, 0x1a46, 0x8, 0x0, 0x0)
github.com/aerospike/aerospike-client-go.(*batchCommandGet).Execute(0xc8e977b920, 0x0, 0x0)
	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command.go:100 +0x29c
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc85a09d890, 0x7fc0ec539138, 0xc8e977b920, 0x0, 0x0)
	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/command.go:1057 +0xa4a
	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command_get.go:101 +0x86f
	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command_get.go:156 +0x68
github.com/aerospike/aerospike-client-go.(*Client).batchExecute.func1(0xc8513f6bd0, 0xc84a765090, 0xc8513f6bf0, 0xc84a117f80, 0xc820128280, 0xc85a09d830)
	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/client.go:1463 +0x86
created by github.com/aerospike/aerospike-client-go.(*Client).batchExecute
	/opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/client.go:1468 +0x2ca
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseResult(0xc8ce2fc410, 0x7fc0ec539138, 0xc8e977b920, 0xc8cb2b32c0, 0x0, 0x0)
panic: runtime error: index out of range
```

**Comment by khaf** [comment]
I think both of these have been fixed before. Please update to the latest master and let me know how it goes.

**Comment by xlab** [comment]
Thanks for the updates, the amount of panics dropped after updating to the master.
However this one in **parseRecordResults** is still here and seems to appear on migration events:

```
panic: runtime error: index out of range
goroutine 8059968 [running]:
panic(0x115e400, 0xc82000a080)
 /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/aerospike/aerospike-client-go.(*batchCommandGet).parseRecordResults(0xc844a56d80, 0x7f73544fc920, 0xc844a56d80, 0x183e, 0x8, 0x0, 0x0)
 /opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command_get.go:99 +0x86f
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseResult(0xca4cbc4f70, 0x7f73544fc920, 0xc844a56d80, 0xc97dfe2a80, 0x0, 0x0)
 /opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command.go:100 +0x29c
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc8ec1823f0, 0x7f73544fc920, 0xc844a56d80, 0x0, 0x0)
 /opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/command.go:1055 +0xb81
github.com/aerospike/aerospike-client-go.(*batchCommandGet).Execute(0xc844a56d80, 0x0, 0x0)
 /opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/batch_command_get.go:149 +0x68
github.com/aerospike/aerospike-client-go.(*Client).batchExecute.func1(0xc891da6670, 0xca8e3840a0, 0xc8c3e91ad8, 0xc9234d44a0, 0xc8430680b0, 0xc8ec182390)
 /opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/client.go:1472 +0x86
created by github.com/aerospike/aerospike-client-go.(*Client).batchExecute
 /opt/xxx/vendor/src/github.com/aerospike/aerospike-client-go/client.go:1477 +0x2ca
 ```

We currently have to insert defers with `recover()` now for this function.

**Comment by khaf** [comment]
Interesting; I can't reproduce the panic. Which version ad edition of the server are you using?

Do you think you can provide a simple code snippet that can reproduce the panic?

**Comment by xlab** [comment]
> Do you think you can provide a simple code snippet that can reproduce the panic?

Sorry, I don't think so, this issue haven't bothered us earlier and occurs on very special circumstances. It seems to be linked with server configuration but I can't be specific there :(

**Comment by khaf** [comment]
Can you say which version and edition of the server you are using?

**Comment by xlab** [comment]
Version 3.7.5.1 Community Edition

**Comment by khaf** [comment]
This should have been taken care of by the last release today. Please let me know in case it happens again.
