### ISSUE TITLE
Panic on a waiting of stabilization

### ISSUE THREAD

**Issue by alxmsl** [aerospike/aerospike-client-go#165]
Revision: `d5e1682cb6e55f007b57dc831c974fee81d88c24`
Branch: `master`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x58ac31]
goroutine 1225 [running]:
panic(0xce2d40, 0xc42000c0c0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/aerospike/aerospike-client-go.(*Cluster).removeNodes.func3(0xc98ac0, 0xc420a65080, 0xc4204defa0, 0x0, 0xc423a0e120, 0xc423575db0)
/go/src/github.com/propellerads/user_data/vendor/src/github.com/aerospike/aerospike-client-go/cluster.go:569 +0x111
github.com/aerospike/aerospike-client-go/types/atomic.(*SyncVal).Update(0xc4204def90, 0xc423575e18, 0x0, 0x0)
/go/src/github.com/propellerads/user_data/vendor/src/github.com/aerospike/aerospike-client-go/types/atomic/sync_val.go:46 +0x95
github.com/aerospike/aerospike-client-go.(*Cluster).removeNodes(0xc4201c2ea0, 0xc4207682c0, 0x6, 0x8)
/go/src/github.com/propellerads/user_data/vendor/src/github.com/aerospike/aerospike-client-go/cluster.go:583 +0x169
github.com/aerospike/aerospike-client-go.(*Cluster).tend(0xc4201c2ea0, 0x0, 0x0, 0x0)
/go/src/github.com/propellerads/user_data/vendor/src/github.com/aerospike/aerospike-client-go/cluster.go:280 +0x5b8
github.com/aerospike/aerospike-client-go.(*Cluster).waitTillStabilized.func1(0xc4201c2ea0, 0x100, 0xc420628228, 0xc42014e230)
/go/src/github.com/propellerads/user_data/vendor/src/github.com/aerospike/aerospike-client-go/cluster.go:326 +0x38
created by github.com/aerospike/aerospike-client-go.(*Cluster).waitTillStabilized
/go/src/github.com/propellerads/user_data/vendor/src/github.com/aerospike/aerospike-client-go/cluster.go:341 +0xb3
```

**Comment by khaf** [comment]
Could you please provide a bit more info regarding your environment?

Which server version, how many nodes, and possibly your config?

**Comment by alxmsl** [comment]
Yes, I could. I have cluster of 4 nodes of `3.9.0.3` aerospike server:
```
$ asadm -e 'info network'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Network Information~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 Node               Node                    Ip       Build   Cluster            Cluster     Cluster         Principal   Client       Uptime
                                    .                 Id                     .           .      Size                Key   Integrity                 .    Conns            .
v-5-519-d5668-125.qwertyuio.pas:3000    BB971F70942A844    NNN.MM.KKK.125:3000   C-3.9.0.3         4   D19D5BF40AA67190   True        BB9C5910842A844     1460   2302:50:29
v-6-07-2-d5667-126.qwertyuio.pas:3000   BB919F60942A844    NNN.MM.KKK.126:3000   C-3.9.0.3         4   D19D5BF40AA67190   True        BB9C5910842A844     1576   2298:23:37
v-6-07-4-d5669-127.qwertyuio.pas:3000   *BB9C5910842A844   NNN.MM.KKK.127:3000   C-3.9.0.3         4   D19D5BF40AA67190   True        BB9C5910842A844     1538   2203:49:19
v-6-16-22-d6363-17.qwertyuio.pas:3000   BB94A8364771814    NNN.MM.KKK.17:3000    C-3.9.0.3         4   D19D5BF40AA67190   True        BB9C5910842A844     1708   2181:23:32
Number of rows: 4
```
Server configuration for example for node `NNN.MM.KKK.125` is:
```
service {
        user root
        group root
        paxos-single-replica-limit 1
        pidfile /var/run/aerospike/asd.pid
        service-threads 32
        transaction-queues 32
        transaction-threads-per-queue 4
        proto-fd-max 100000
        paxos-recovery-policy auto-reset-master
}

logging {
        file /var/log/aerospike/aerospike.log {
                context any info
        }
}

network {
        service {
                address any
                port 3000
        }

        heartbeat {
                mode multicast
                address PPP.2.2.2
                port 9918
                interface-address NNN.MM.KKK.125
                interval 150
                timeout 10
        }

        fabric {
                port 3001
        }

        info {
                port 3003
        }
}

namespace test {
        replication-factor 2
        memory-size 4G
        default-ttl 30d

        storage-engine device {
                file /opt/aerospike/data/test.dat
                filesize 12G
                data-in-memory true
        }
}

namespace ssd0 {
        ldt-enabled true
        replication-factor 2
        memory-size 188G
        default-ttl 10d
        storage-engine device {
                device /dev/nvme0n1
		device /dev/nvme1n1
                write-block-size 128K
        }
}
```
Other servers' configurations are the same. 
Client policy:
```
aerospike.ClientPolicy{
	ConnectionQueueSize:         256,
	LimitConnectionsToQueueSize: false,
}
```

**Comment by khaf** [comment]
This issue is addressed in the latest release and should not occur anymore.
