### ISSUE TITLE
Panic on ScanAll while upgrade/rebalance

### ISSUE THREAD

**Issue by powerman** [aerospike/aerospike-client-go#166]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5161c9]

goroutine 51018 [running]:
panic(0x9467c0, 0xc420012060)
      /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/aerospike/aerospike-client-go.(*Node).getConnection(0x0, 0x0, 0xc80e00, 0x45ea13, 0x58493fb1)
      /tmp/build/a94a8fe5/src/github.com/aerospike/aerospike-client-go/node.go:435 +0x29
github.com/aerospike/aerospike-client-go.(*Node).GetConnection(0x0, 0x0, 0xc4202358c0, 0x0, 0x0)
      /tmp/build/a94a8fe5/src/github.com/aerospike/aerospike-client-go/node.go:416 +0xaa
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc4202358c0, 0xc62140, 0xc4202358c0, 0xc4202358c0, 0xc420072200)
      /tmp/build/a94a8fe5/src/github.com/aerospike/aerospike-client-go/command.go:1205 +0x1ca
github.com/aerospike/aerospike-client-go.(*scanCommand).Execute(0xc4202358c0, 0x0, 0x0)
      /tmp/build/a94a8fe5/src/github.com/aerospike/aerospike-client-go/scan_command.go:66 +0x7f
github.com/aerospike/aerospike-client-go.(*Client).scanNode(0xc420236bd0, 0xc42042bc60, 0x0, 0xc424df3dc0, 0x9dff25, 0x9, 0x9dfb62, 0x9, 0x923505ce87c32a1f, 0x0, ...)
      /tmp/build/a94a8fe5/src/github.com/aerospike/aerospike-client-go/client.go:456 +0x112
github.com/aerospike/aerospike-client-go.(*Client).ScanAll.func2(0xc4200ae6f0, 0x2, 0x2, 0xc420236bd0, 0xc42042bc60, 0xc424df3dc0, 0x9dff25, 0x9, 0x9dfb62, 0x9, ...)
      /tmp/build/a94a8fe5/src/github.com/aerospike/aerospike-client-go/client.go:420 +0xf1
created by github.com/aerospike/aerospike-client-go.(*Client).ScanAll
      /tmp/build/a94a8fe5/src/github.com/aerospike/aerospike-client-go/client.go:425 +0x366
Error running handler: exit status 2
```

Aerospike cluster includes two instances. One instance was stopped for 5 min due to upgrade purposes and after that it was started with normal start. Database on both nodes was consistent. After upgraded node start Aerospike cluster performs re-balancing between two nodes and migration that takes a little resources for 5-10 minutes.

Here is relevant part of our code, just in case:

```go
func ScanStatus() <-chan *StatusRecord {
	scanTime := time.Now()
	scanPolicy := aspk.NewScanPolicy()
	scanPolicy.RecordQueueSize = 3000000 // tuned for 10M records
	scanPolicy.ConcurrentNodes = false   // WTF? false is faster!
	rs, err := Client.ScanAll(scanPolicy, common.AspkStatusNS, common.AspkStatusSet)
	if err != nil {
		aspkErrTotal.With(prometheus.Labels{setLabel: setLabelStatus, opLabel: opLabelScan}).Inc()
		log.Err(err)
		return nil
	}
	results := make(chan *StatusRecord, 1)
	go func(in <-chan *aspk.Result, out chan<- *StatusRecord) {
		defer rs.Close()
		defer close(out)
		for res := range rs.Results() {
			if res.Err != nil {
				aspkErrTotal.With(prometheus.Labels{setLabel: setLabelStatus, opLabel: opLabelScanResult}).Inc()
// ---> next line outputs "Cluster key mismatch" to log in 0.04 sec before crash
				log.Err(res.Err)
				return
			}
			out <- newStatusRecord(res.Record, scanTime)
		}
		scanDuration.Observe(time.Since(scanTime).Seconds())
	}(rs.Results(), results)
	return results
}
```

**Comment by khaf** [comment]
Thanks for your report. Is this a singular panic or is it recurrent?

**Comment by powerman** [comment]
For now only one such panic happens, but we're in the middle of aerospike upgrade process, so there may be more soon. BTW, crashed code was built today at 07:57 GMT with current master of aerospike-client-go at that moment.

**Comment by powerman** [comment]
We've just got exactly same panic in about two minutes after restarting second node, this time without "Cluster key mismatch" in log. The listed above ScanStatus() is executed every 1 minute.

**Comment by khaf** [comment]
This issue is addressed in the latest release and should not occur again.

**Comment by powerman** [comment]
Thanks!
