### ISSUE TITLE
panic: panic: runtime error: invalid memory address or nil pointer dereference - github.com/aerospike/aerospike-client-go.(*Connection).IsConnected(...)

### ISSUE THREAD

**Issue by cgebe** [aerospike/aerospike-client-go#244]
I have around ~20 workers executing search queries every second. 
Client connections are failing due to a panic - current master:

```
signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x811d11]
goroutine 2601 [running]:
github.com/aerospike/aerospike-client-go.(*Connection).IsConnected(...) 
 	/go/src/github.com/aerospike/aerospike-client-go/connection.go:230
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc4212d6780, 0xcaa100, 0xc4212d6780, 0xc422297f01, 0x859dc5, 0xc4234ffb10)
	/go/src/github.com/aerospike/aerospike-client-go/command.go:1686 +0x7c1
github.com/aerospike/aerospike-client-go.(*queryCommand).Execute(0xc4212d6780, 0x0, 0x0)
	/go/src/github.com/aerospike/aerospike-client-go/query_command.go:47 +0x77
github.com/aerospike/aerospike-client-go.(*Client).Query.func1(0xc4212d6780)
	/go/src/github.com/aerospike/aerospike-client-go/client.go:773 +0x2d
created by github.com/aerospike/aerospike-client-go.(*Client).Query
	/go/src/github.com/aerospike/aerospike-client-go/client.go:772 +0x112
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x811d11]
goroutine 24778 [running]:
github.com/aerospike/aerospike-client-go.(*Connection).IsConnected(...)
	/go/src/github.com/aerospike/aerospike-client-go/connection.go:230
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc42000e140, 0xcaa100, 0xc42000e140, 0xc422ab5701, 0x859dc5, 0xc42179cbe0)
	/go/src/github.com/aerospike/aerospike-client-go/command.go:1686 +0x7c1
github.com/aerospike/aerospike-client-go.(*queryCommand).Execute(0xc42000e140, 0x0, 0x0)
	/go/src/github.com/aerospike/aerospike-client-go/query_command.go:47 +0x77
github.com/aerospike/aerospike-client-go.(*Client).Query.func1(0xc42000e140)
	/go/src/github.com/aerospike/aerospike-client-go/client.go:773 +0x2d
created by github.com/aerospike/aerospike-client-go.(*Client).Query
	/go/src/github.com/aerospike/aerospike-client-go/client.go:772 +0x112
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x811d11]
goroutine 24781 [running]:
github.com/aerospike/aerospike-client-go.(*Connection).IsConnected(...)
	/go/src/github.com/aerospike/aerospike-client-go/connection.go:230
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc420511040, 0xcaa100, 0xc420511040, 0xc4221f3701, 0x859dc5, 0xc42179cbe0)
	/go/src/github.com/aerospike/aerospike-client-go/command.go:1686 +0x7c1
github.com/aerospike/aerospike-client-go.(*queryCommand).Execute(0xc420511040, 0x0, 0x0)
	/go/src/github.com/aerospike/aerospike-client-go/query_command.go:47 +0x77
github.com/aerospike/aerospike-client-go.(*Client).Query.func1(0xc420511040)
	/go/src/github.com/aerospike/aerospike-client-go/client.go:773 +0x2d
created by github.com/aerospike/aerospike-client-go.(*Client).Query
	/go/src/github.com/aerospike/aerospike-client-go/client.go:772 +0x112 
```

**Comment by khaf** [comment]
Please use v1.35.1 and see if the same problem happens there as well.

**Comment by khaf** [comment]
This is fixed in the latest commit. Let me know how it goes. Do you by any chance see any high memory utilization in the client that you can't explain?

**Comment by cgebe** [comment]
looks good now, no anomalies
