### ISSUE TITLE
Panic .updateDeadline

### ISSUE THREAD

**Issue by un000** [aerospike/aerospike-client-go#352]
Server version 5.6.0.5
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x76c18b]

github.com/aerospike/aerospike-client-go/v5.(*Connection).updateDeadline(0xc024aff2c0, 0xc01397f1a8, 0xc0172e7418)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/connection.go:281 +0xab
github.com/aerospike/aerospike-client-go/v5.(*Connection).Read(0xc024aff2c0, 0xc032140000, 0x10000, 0x10000, 0x8, 0x7c4bd0, 0x1b3aae0, 0xfeca40)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/connection.go:214 +0x45
github.com/aerospike/aerospike-client-go/v5.(*readCommand).parseResult(0xc1392b2000, 0x142ce58, 0xc1392b2000, 0xc024aff2c0, 0x0, 0x0)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/read_command.go:85 +0x6e
github.com/aerospike/aerospike-client-go/v5.(*baseCommand).executeAt(0xc1392b2000, 0x142ce58, 0xc1392b2000, 0xc1392a0cf0, 0xc1392a0c00, 0xc025c5716206aeb8, 0x4e8c40653, 0x1b56a80, 0x0, 0x0, ...)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/command.go:2128 +0xc0f
github.com/aerospike/aerospike-client-go/v5.(*baseCommand).execute(0xc1392b2000, 0x142ce58, 0xc1392b2000, 0xc1373ebd00, 0x7, 0x7)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/command.go:1970 +0xda
github.com/aerospike/aerospike-client-go/v5.(*operateCommand).Execute(...)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/operate_command.go:79
github.com/aerospike/aerospike-client-go/v5.(*Client).Operate(0xc000142540, 0xc1392a0cf0, 0xc1373cd380, 0xc1373ebdc0, 0x7, 0x7, 0x0, 0xc1373ebdc0, 0x4)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/client.go:481 +0x1b2
````

```
	aerospikeHosts, err := aerospike.NewHosts(c.config.Addresses...)
	if err != nil {
		return err
	}

	cp := aerospike.NewClientPolicy()
	cp.Timeout = 5 * time.Second
	cp.IdleTimeout = 30 * time.Second
	cp.ConnectionQueueSize = 2048
	cp.MaxErrorRate = 8000
	cp.ErrorRateWindow = 5
	cp.MinConnectionsPerNode = 1024

	client, err := aerospike.NewClientWithPolicyAndHost(cp, aerospikeHosts...)
	if err != nil {
		return fmt.Errorf("error creating aerospike client: %w", err)
	}
	c.client = client

	conns := cp.MinConnectionsPerNode
	_, err = c.client.WarmUp(conns)
	if err != nil {
		return fmt.Errorf("error warming up connections: %w", err)
	}
```

**Comment by khaf** [comment]
The error here is coming from a read command (e.g. `client.Get(...)`) and is not related to the code snippet posted. Can you please paste the panic message (before the first line of the stack trace)?

**Comment by un000** [comment]
But there was the only one panic after millions of requests, right after an application started.

The panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x76c18b]

goroutine 13426 [running]:
github.com/aerospike/aerospike-client-go/v5.(*Connection).updateDeadline(0xc024aff2c0, 0xc01397f1a8, 0xc0172e7418)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/connection.go:281 +0xab
github.com/aerospike/aerospike-client-go/v5.(*Connection).Read(0xc024aff2c0, 0xc032140000, 0x10000, 0x10000, 0x8, 0x7c4bd0, 0x1b3aae0, 0xfeca40)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/connection.go:214 +0x45
github.com/aerospike/aerospike-client-go/v5.(*readCommand).parseResult(0xc1392b2000, 0x142ce58, 0xc1392b2000, 0xc024aff2c0, 0x0, 0x0)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/read_command.go:85 +0x6e
github.com/aerospike/aerospike-client-go/v5.(*baseCommand).executeAt(0xc1392b2000, 0x142ce58, 0xc1392b2000, 0xc1392a0cf0, 0xc1392a0c00, 0xc025c5716206aeb8, 0x4e8c40653, 0x1b56a80, 0x0, 0x0, ...)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/command.go:2128 +0xc0f
github.com/aerospike/aerospike-client-go/v5.(*baseCommand).execute(0xc1392b2000, 0x142ce58, 0xc1392b2000, 0xc1373ebd00, 0x7, 0x7)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/command.go:1970 +0xda
github.com/aerospike/aerospike-client-go/v5.(*operateCommand).Execute(...)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/operate_command.go:79
github.com/aerospike/aerospike-client-go/v5.(*Client).Operate(0xc000142540, 0xc1392a0cf0, 0xc1373cd380, 0xc1373ebdc0, 0x7, 0x7, 0x0, 0xc1373ebdc0, 0x4)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/client.go:481 +0x1b2
```

```
c.emptyList = []int64{}
c.lp = aero.NewListPolicy(aero.ListOrderOrdered, aero.ListWriteFlagsDefault)
c.mp = aero.NewMapPolicyWithFlags(aero.MapOrder.UNORDERED, aero.MapWriteFlagsCreateOnly|aero.MapWriteFlagsNoFail)

id := int64(123)
now := time.Now().UTC().Unix()
ctxKey := aero.CtxMapKey(aero.NewIntegerValue(int(id)))
res, err := c.aero.Operate(
			context.Background(),
			"dmp.save_event",
			key, c.ttl, aero.UPDATE,
			aero.MapPutOp(
				c.mp,
			         "cri",
			         123, c.emptyList,
			),
			aero.ListSetOrderOp("cri", aero.ListOrderOrdered, ctxKey),
			aero.ListAppendWithPolicyContextOp(c.lp, "cri" , []*aero.CDTContext{ctxKey}, now),
			aero.ListRemoveByValueRangeOp(
			"cri", aero.ListReturnTypeNone,
				nil, now-86400,
				ctxKey,
			),
			aero.MapRemoveByRankRangeOp("cri", 512, aero.MapReturnType.NONE),
			aero.MapRemoveByValueOp("cri", c.emptyList, aero.MapReturnType.NONE),
			aero.GetBinOp("cri"),
		)
```

**Comment by un000** [comment]
it happens more often than once 
![image](https://user-images.githubusercontent.com/19488486/120463402-8ea28300-c3a4-11eb-9ebb-2be9662198be.png)

**Comment by un000** [comment]
And one more recoverable panic.
```
runtime error: invalid memory address or nil pointer dereference
        

runtime.gopanic
            /usr/local/go/src/runtime/panic.go:965
runtime.panicmem
            /usr/local/go/src/runtime/panic.go:212
runtime.sigpanic
            /usr/local/go/src/runtime/signal_unix.go:734
github.com/aerospike/aerospike-client-go/v5.(*Connection).updateDeadline
            /go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/connection.go:281
github.com/aerospike/aerospike-client-go/v5.(*Connection).Read
            /go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/connection.go:214
github.com/aerospike/aerospike-client-go/v5.(*readCommand).parseResult
            /go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/read_command.go:85
github.com/aerospike/aerospike-client-go/v5.(*baseCommand).executeAt
            /go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/command.go:2128
github.com/aerospike/aerospike-client-go/v5.(*baseCommand).execute
            /go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/command.go:1970
github.com/aerospike/aerospike-client-go/v5.(*readCommand).Execute
            /go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/read_command.go:264
github.com/aerospike/aerospike-client-go/v5.(*Client).GetObject
            /go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/client_reflect.go:74
github.com/valyala/fasthttp.(*workerPool).getCh.func1
```

GetObject struct:
```
struct {
  Cri map[int64]int64 `json:"cri"`
}

**Comment by khaf** [comment]
I have no idea why this error happens, since it should be impossible to happen. Any ideas regards the state of the cluster when it happens? Do you have a lot of migrations?

**Comment by un000** [comment]
> I have no idea why this error happens, since it should be impossible to happen. Any ideas regards the state of the cluster when it happens? Do you have a lot of migrations?

Nope a cluster is stable. Requests are uniform. 

Maybe we have a race condition with the following parameter:
```	
cp.MinConnectionsPerNode = 1024
```
We have set it after upgrading to the 5.x lib. `MinConnectionsPerNode` fixed our latency issues.
Also we have upgraded aerospike from 4.8 -> 5.6 at the same time.

![image](https://user-images.githubusercontent.com/19488486/120494679-aee23a00-c3c4-11eb-87af-8255b744c14a.png)

**Comment by un000** [comment]
Another one, when a node was added to the cluster.
```
{"level":"info","ts":"2021-06-02T13:36:36.851Z","caller":"aerospike/logger.go:19","msg":"Node `BB91317BC645DD4 10.10.2.110:3000` refresh failed: `ResultCode: NETWORK_ERROR, Iteration: 0, InDoubt: false, Node: <nil>: network error. Checked the wrapped error for detail\nResultCode: NETWORK_ERROR, Iteration: 0, InDoubt: false, Node: <nil>: network error. Checked the wrapped error for detail\nread tcp 10.233.72.152:53010->10.10.2.110:3000: read: connection reset by peer`","version":"ef24336b","system":"aerospike"}
{"level":"info","ts":"2021-06-02T13:36:36.859Z","caller":"aerospike/logger.go:19","msg":"Tend finished. Live node count changes from 4 to 3","version":"ef24336b","system":"aerospike"}
{"level":"info","ts":"2021-06-02T13:36:36.859Z","caller":"aerospike/logger.go:19","msg":"Tending took 2.185429396s, while your requested ClientPolicy.TendInterval is 1s. Tends are slower than the interval, and may be falling behind the changes in the cluster.","version":"ef24336b","system":"aerospike"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x76906f]

goroutine 61673727 [running]:
github.com/aerospike/aerospike-client-go/v5.(*baseCommand).executeAt(0xc148e9a6c0, 0x142d268, 0xc148e9a6c0, 0xc1381b79e0, 0xc1381b7901, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/command.go:2041 +0x2ef
github.com/aerospike/aerospike-client-go/v5.(*baseCommand).execute(0xc148e9a6c0, 0x142d268, 0xc148e9a6c0, 0xc0115a4901, 0xc11c1144f0, 0x0)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/command.go:1970 +0xda
github.com/aerospike/aerospike-client-go/v5.(*baseMultiCommand).execute(...)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/multi_command.go:366
github.com/aerospike/aerospike-client-go/v5.(*scanPartitionCommand).Execute(0xc148e9a6c0, 0x0, 0xc03da3e768)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/scan_partition_command.go:65 +0x47
github.com/aerospike/aerospike-client-go/v5.(*werrGroup).execute.func1(0xc054adaa00, 0x142d268, 0xc148e9a6c0)
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/werrgroup.go:62 +0xc6
created by github.com/aerospike/aerospike-client-go/v5.(*werrGroup).execute
/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.0.2/werrgroup.go:55 +0xaf
```

**Comment by khaf** [comment]
The last issue is related to ticket #353 . I have already found and fixed it.

**Comment by un000** [comment]
Something happens when one of the servers is going down. Tested with restarts.

**Comment by khaf** [comment]
This took unusually long to figure out, since I was looking in the wrong place. The actual reason was shadowing of errors. Fixed in v5.1.0.

**Comment by un000** [comment]
Thank you! I've upgraded and will be watching for a some period for errors.

**Comment by un000** [comment]
Looks nice. Panics gone away.
