### ISSUE TITLE
panic: unaligned 64-bit atomic operation in Cluster.tend (running on 

### ISSUE THREAD

**Issue by ncabatoff** [aerospike/aerospike-client-go#401]
In the [Vault repo](github.com/hashicorp/vault) we run nightly tests with 32bit builds (GOARCH=386), and last night observed this panic in our [TestAerospikeBackend](https://github.com/hashicorp/vault-enterprise/blob/main/physical/aerospike/aerospike_test.go#L18-L18):

```
panic: unaligned 64-bit atomic operation

goroutine 28 [running]:
runtime/internal/atomic.panicUnaligned()
	/home/runner/actions-runner/_work/_tool/go/1.20.3/x64/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Load64(0x90f0694)
	/home/runner/actions-runner/_work/_tool/go/1.20.3/x64/src/runtime/internal/atomic/atomic_386.s:225 +0x10
github.com/aerospike/aerospike-client-go/v5/internal/atomic.(*Int).Get(...)
	/home/runner/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.6.0/internal/atomic/int.go:53
github.com/aerospike/aerospike-client-go/v5.(*Node).verifyPeersGeneration(0x90f0600, 0x9404020, 0x9097e30)
	/home/runner/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.6.0/node.go:305 +0x113
github.com/aerospike/aerospike-client-go/v5.(*Node).Refresh(0x90f0600, 0x9097e30)
	/home/runner/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.6.0/node.go:145 +0x22b
github.com/aerospike/aerospike-client-go/v5.(*Cluster).tend.func1(0x90f0600)
	/home/runner/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.6.0/cluster.go:261 +0x68
created by github.com/aerospike/aerospike-client-go/v5.(*Cluster).tend
	/home/runner/go/pkg/mod/github.com/aerospike/aerospike-client-go/v5@v5.6.0/cluster.go:259 +0x29c
```

Technically the failure was in the vault-enterprise repo, but I don't believe there's anything specific to it, we just don't run these nightly 32-bit tests on the OSS repo.

Our go.mod has
```
github.com/aerospike/aerospike-client-go/v5 v5.6.0
```

**Comment by ncabatoff** [comment]
Hi @khaf, sorry I missed your reply.

> Is vault used on 32bit extensively with Aerospike?

I have no way of knowing.  My assumption is that vault isn't used on 32-bit much at all, with Aerospike or otherwise, but that's a guess.  Maybe I should have the nightly 32bit tests skip Aerospike, and we should flag it as unsupported for 32-bit archs in our docs.

**Comment by khaf** [comment]
Hi @ncabatoff , thank you for following up. Yes I believe marking it as unsupported and disabling the tests for 32bit would be the better course of action for now.

**Comment by ncabatoff** [comment]
> Hi @ncabatoff , thank you for following up. Yes I believe marking it as unsupported and disabling the tests for 32bit would be the better course of action for now.

I've done so.  I'll close this issue now, since you don't support 32-bit.  Thanks!
