### ISSUE TITLE
panic: Invalid size for buffer: 38780866783

### ISSUE THREAD

**Issue by clanstyles** [aerospike/aerospike-client-go#92]
Randomly getting this causing panics in my application.

**Comment by GeertJohan** [comment]
Does it have a stack trace with it?

**Comment by ClanStyles** [comment]
```
panic: Invalid size for buffer: 38780866783

goroutine 134 [running]:
main.GetPublisherDashboard.func1(0xc820583660, 0xc82053c8a0, 0xc82058cc00)
	/gocode/src/panel/publishers.go:30 +0x130
created by main.GetPublisherDashboard
	/gocode/src/panel/publishers.go:34 +0xac

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fda186e9ef0, 0x72, 0xc82000a210)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82019a3e0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82019a3e0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82019a380, 0x0, 0x7fda186a50d8, 0xc82052e0e0)
	/usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201820d8, 0x458280, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8201820d8, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820194c00, 0x7fda186a50a0, 0xc8201820d8, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820194c00, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1877 +0x136
github.com/labstack/echo.(*Echo).run(0xc8200a1540, 0xc820194c00, 0x0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/labstack/echo/echo.go:517 +0x4a
github.com/labstack/echo.(*Echo).Run(0xc8200a1540, 0xa04028, 0x5)
	/home/styles/Code/golang/src/github.com/labstack/echo/echo.go:496 +0x5e
main.main()
	/gocode/src/panel/server.go:126 +0x15d2

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 41 [IO wait]:
net.runtime_pollWait(0x7fda186e9e30, 0x72, 0xc82000a210)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82020a840, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020a840, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020a7e0, 0xc820256000, 0x1000, 0x1000, 0x0, 0x7fda1a549050, 0xc82000a210)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201cc170, 0xc820256000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc8202000f8, 0xc820256000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc8201bcbc0, 0xc820256000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc8201e44e0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc8201e44e0, 0xc81fff360a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc8201e44e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8202d98f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8202d98f0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc8201e44e0, 0xc820192b60, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8202000b0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8202000b0)
	/usr/lib/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1910 +0x3f6

goroutine 25 [select]:
github.com/aerospike/aerospike-client-go.(*Cluster).clusterBoss(0xc8201c6200, 0xc8201ce8c0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/cluster.go:115 +0x2b4
created by github.com/aerospike/aerospike-client-go.NewCluster
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/cluster.go:97 +0x622

goroutine 67 [IO wait]:
net.runtime_pollWait(0x7fda186e9770, 0x72, 0xc82000a210)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82030b720, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82030b720, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82030b6c0, 0xc820531000, 0x1000, 0x1000, 0x0, 0x7fda1a549050, 0xc82000a210)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8203be018, 0xc820531000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc8203bc258, 0xc820531000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc8202d58c0, 0xc820531000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc8203480c0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc8203480c0, 0xc81fff360a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc8203480c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820536060, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820536060, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc8203480c0, 0xc820192a80, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8203bc210, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8203bc210)
	/usr/lib/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1910 +0x3f6

goroutine 66 [IO wait]:
net.runtime_pollWait(0x7fda186e9fb0, 0x72, 0xc82000a210)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82030b6b0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82030b6b0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82030b650, 0xc820377000, 0x1000, 0x1000, 0x0, 0x7fda1a549050, 0xc82000a210)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8203be010, 0xc820377000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc8203bc1a8, 0xc820377000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc8202d5880, 0xc820377000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820348060)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820348060, 0xc81fff1d0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc820348060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8205ae5d0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8205ae5d0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820348060, 0xc8201c4380, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8203bc160, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8203bc160)
	/usr/lib/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1910 +0x3f6

goroutine 13 [chan send]:
github.com/aerospike/aerospike-client-go.(*Recordset).Results.func1(0xc8202ee200, 0xc82001c720)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/recordset.go:101 +0x21b
created by github.com/aerospike/aerospike-client-go.(*Recordset).Results
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/recordset.go:105 +0x6f

goroutine 16 [chan send]:
github.com/aerospike/aerospike-client-go.(*Recordset).Results.func1(0xc8202ee300, 0xc82001c8a0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/recordset.go:101 +0x21b
created by github.com/aerospike/aerospike-client-go.(*Recordset).Results
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/recordset.go:105 +0x6f

goroutine 82 [semacquire]:
sync.runtime_Semacquire(0xc82058366c)
	/usr/lib/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc820583660)
	/usr/lib/go/src/sync/waitgroup.go:126 +0xb4
main.GetPublisherDashboard(0xc82053c8a0, 0x0, 0x0)
	/gocode/src/panel/publishers.go:110 +0x1ea
main.AuthRequired.func1.1(0xc82053c8a0, 0x0, 0x0)
	/gocode/src/panel/middleware.go:40 +0x5b5
github.com/labstack/echo/middleware.Gzip.func1.1(0xc82053c8a0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/labstack/echo/middleware/compress.go:67 +0x3dd
github.com/syntaqx/echo-middleware/session.Sessions.func1.1(0xc82053c8a0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/syntaqx/echo-middleware/session/session.go:76 +0x26e
github.com/labstack/echo.wrapHandlerFuncMW.func1.1(0xc82053c8a0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/labstack/echo/echo.go:587 +0x7d
github.com/labstack/echo.wrapHandlerFuncMW.func1.1(0xc82053c8a0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/labstack/echo/echo.go:587 +0x7d
github.com/labstack/echo/middleware.Recover.func1.1(0xc82053c8a0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/labstack/echo/middleware/recover.go:25 +0x66
github.com/labstack/echo/middleware.Logger.func1.1(0xc82053c8a0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/labstack/echo/middleware/logger.go:28 +0x113
github.com/labstack/echo.(*Echo).ServeHTTP(0xc82024e1e0, 0x7fda186ea340, 0xc8203bc0b0, 0xc8203ac2a0)
	/home/styles/Code/golang/src/github.com/labstack/echo/echo.go:476 +0x246
net/http.serverHandler.ServeHTTP(0xc820194c00, 0x7fda186ea340, 0xc8203bc0b0, 0xc8203ac2a0)
	/usr/lib/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82053a000)
	/usr/lib/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1910 +0x3f6

goroutine 52 [chan send]:
github.com/aerospike/aerospike-client-go.(*Recordset).Results.func1(0xc82029e200, 0xc82034c120)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/recordset.go:101 +0x21b
created by github.com/aerospike/aerospike-client-go.(*Recordset).Results
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/recordset.go:105 +0x6f

goroutine 83 [IO wait]:
net.runtime_pollWait(0x7fda186e9830, 0x72, 0xc82000a210)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8205340d0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8205340d0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820534070, 0xc820544000, 0x1000, 0x1000, 0x0, 0x7fda1a549050, 0xc82000a210)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820538008, 0xc820544000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc82053a0f8, 0xc820544000, 0x1000, 0x1000, 0x434ddd, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82052e080, 0xc820544000, 0x1000, 0x1000, 0xc8200118c0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc82053c060)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82053c060, 0xc81fff360a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc82053c060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820152150, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820152150, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc82053c060, 0xc820192c40, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc82053a0b0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc82053a0b0)
	/usr/lib/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1910 +0x3f6

goroutine 84 [IO wait]:
net.runtime_pollWait(0x7fda186e96b0, 0x72, 0xc82000a210)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820534140, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820534140, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205340e0, 0xc82054a000, 0x1000, 0x1000, 0x0, 0x7fda1a549050, 0xc82000a210)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820538010, 0xc82054a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc82053a1a8, 0xc82054a000, 0x1000, 0x1000, 0x580, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82052e0c0, 0xc82054a000, 0x1000, 0x1000, 0x11, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc82053c0c0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82053c0c0, 0xc81ffe290a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc82053c0c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820152000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820152000, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc82053c0c0, 0xc8203ac000, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc82053a160, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc82053a160)
	/usr/lib/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1910 +0x3f6

goroutine 136 [runnable]:
reflect.Value.Type(0x981540, 0xc820533740, 0xd9, 0x9a43a0, 0x9a0580)
	/usr/lib/go/src/reflect/value.go:1661
github.com/aerospike/aerospike-client-go.setValue(0x981540, 0xc820533740, 0xd9, 0x842580, 0xc82058cc30, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/read_command.go:491 +0x4bca
github.com/aerospike/aerospike-client-go.setValue(0x8301e0, 0xc8202eee10, 0xd7, 0x831e60, 0xc8205abba0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/read_command.go:447 +0xa1a
github.com/aerospike/aerospike-client-go.(*readCommand).setObjectField(0xc82017ed20, 0x9699e0, 0xc8202eee00, 0xd9, 0xa062a8, 0x6, 0x831e60, 0xc8205abba0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/read_command.go:236 +0x1c6
github.com/aerospike/aerospike-client-go.(*readCommand).parseObject(0xc82017ed20, 0x3, 0x0, 0x1, 0x278a1f, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/read_command.go:207 +0x50e
github.com/aerospike/aerospike-client-go.(*readCommand).parseResult(0xc82017ed20, 0x7fda186ea6b8, 0xc82017ed20, 0xc8202dc900, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/read_command.go:116 +0xd26
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc820152630, 0x7fda186ea6b8, 0xc82017ed20, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/command.go:1041 +0x9e7
github.com/aerospike/aerospike-client-go.(*readCommand).Execute(0xc82017ed20, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/read_command.go:222 +0x68
github.com/aerospike/aerospike-client-go.(*Client).GetObject(0xc820179140, 0xc820176800, 0xc82017ecd0, 0x9178c0, 0xc8202eee00, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/client.go:315 +0x4ea
adwize.net/styles/publisher.GetByEmail(0xc82053c8a0, 0xc8205ab9a0, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00000000, ...)
	/gocode/src/publisher/publisher.go:36 +0x2a8
adwize.net/styles/stats.SubIDs(0xc82053c8a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gocode/src/stats/helper.go:36 +0x4e6
adwize.net/styles/stats.ImpressionsToday(0xc82053c8a0, 0xb0ee98, 0x0, 0x0)
	/gocode/src/stats/impressions.go:26 +0x274
main.GetPublisherDashboard.func3(0xc820583660, 0xc82053c8a0, 0xc82058cc00)
	/gocode/src/panel/publishers.go:49 +0xe9
created by main.GetPublisherDashboard
	/gocode/src/panel/publishers.go:55 +0x10e

goroutine 137 [runnable]:
syscall.Syscall(0x1, 0x2, 0xc820184500, 0x4a, 0x4a, 0x4a, 0x0)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.write(0x2, 0xc820184500, 0x4a, 0x80, 0x1, 0x0, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:1064 +0x5f
syscall.Write(0x2, 0xc820184500, 0x4a, 0x80, 0xb, 0x0, 0x0)
	/usr/lib/go/src/syscall/syscall_unix.go:176 +0x4d
os.(*File).write(0xc820032018, 0xc820184500, 0x4a, 0x80, 0x0, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:232 +0xaa
os.(*File).Write(0xc820032018, 0xc820184500, 0x4a, 0x80, 0xd06a20, 0x0, 0x0)
	/usr/lib/go/src/os/file.go:139 +0x8a
log.(*Logger).Output(0xc820014190, 0x2, 0xc82059e0c0, 0x36, 0x0, 0x0)
	/usr/lib/go/src/log/log.go:166 +0x37a
log.Printf(0xa85940, 0x1f, 0xc820055df8, 0x2, 0x2)
	/usr/lib/go/src/log/log.go:289 +0x80
main.un(0xa61ef0, 0x13, 0xecdd45a4e, 0x29647d77, 0xd06a20)
	/gocode/src/panel/trace.go:15 +0x1fa
main.GetPublisherDashboard.func4(0xc820583660, 0xc82053c8a0, 0xc82058cc00)
	/gocode/src/panel/publishers.go:64 +0x130
created by main.GetPublisherDashboard
	/gocode/src/panel/publishers.go:68 +0x144

goroutine 138 [IO wait]:
net.runtime_pollWait(0x7fda186e9bf0, 0x72, 0xc82000a210)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820394060, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820394060, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820394000, 0xc82038c000, 0x1e, 0x4000, 0x0, 0x7fda1a549050, 0xc82000a210)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8202b6010, 0xc82038c000, 0x1e, 0x4000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
github.com/aerospike/aerospike-client-go.(*Connection).Read(0xc8202dc380, 0xc82038c000, 0x4000, 0x4000, 0x1e, 0x0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/connection.go:91 +0xc7
github.com/aerospike/aerospike-client-go.(*readCommand).parseResult(0xc82017ec80, 0x7fda186ea6b8, 0xc82017ec80, 0xc8202dc380, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/read_command.go:59 +0x85
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc8201525d0, 0x7fda186ea6b8, 0xc82017ec80, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/command.go:1041 +0x9e7
github.com/aerospike/aerospike-client-go.(*readCommand).Execute(0xc82017ec80, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/read_command.go:222 +0x68
github.com/aerospike/aerospike-client-go.(*Client).GetObject(0xc820179140, 0xc820176800, 0xc82017ec30, 0x9178c0, 0xc8202eecc0, 0x0, 0x0)
	/home/styles/Code/golang/src/github.com/aerospike/aerospike-client-go/client.go:315 +0x4ea
adwize.net/styles/publisher.GetByEmail(0xc82053c8a0, 0xc8205ab9a0, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00000000, ...)
	/gocode/src/publisher/publisher.go:36 +0x2a8
adwize.net/styles/stats.SubIDs(0xc82053c8a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gocode/src/stats/helper.go:36 +0x4e6
adwize.net/styles/stats.InstallGraph(0xc82053c8a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gocode/src/stats/installs.go:137 +0x371
main.GetPublisherDashboard.func5(0xc820583660, 0xc82053c8a0, 0xc82058cc00)
	/gocode/src/panel/publishers.go:76 +0xe9
created by main.GetPublisherDashboard
	/gocode/src/panel/publishers.go:82 +0x17a

goroutine 139 [running]:
	goroutine running on other thread; stack unavailable
created by main.GetPublisherDashboard
	/gocode/src/panel/publishers.go:94 +0x1b0
```

**Comment by khaf** [comment]
Weird, the stack trace doesn't show the trace it is supposed to. Which version of Go are you using? Are you sure you are using the latest client release?

**Comment by ClanStyles** [comment]
The package commit id is 96b4289bd745ac8c3df7c0c3bf1a2f1fd933abf5 and the Go version is go version go1.5 linux/amd64

**Comment by khaf** [comment]
Seems like the panic is happening in your own app, right? I thought it was happening in the library.

Can you provide a small snippet that shows the operation in which this is happening? (Put/Get/Qhery?)

**Comment by khaf** [comment]
Any news? Would you elaborate on which type of operation you were getting that error?

**Comment by khaf** [comment]
The new release includes some improvements in error handling and fault tolerance. Please give it a try and let me know if you still encounter this problem.
